function result = runSingleSimulation3D(cfg,scenario,noiseVarianceOverride)
%RUNSINGLESIMULATION3D One geometry -> h_true -> pilot -> LS -> NMSE run.
if nargin < 2 || isempty(scenario)
    scenario = generateScenario3D(cfg);
end
[h_true,pathInfo] = generateRayTracingChannels3D(scenario,cfg);
K = size(scenario.UEpos,1);
[p,pilotAssignment] = generatePilots(cfg,K,scenario.UEpos);
activeUE = selectPilotUsers(cfg.pilotUserMode,pathInfo,K);
pilotEnergy = cfg.pilotEnergy*ones(1,K);
if nargin >= 3 && ~isempty(noiseVarianceOverride)
    noiseVariance = noiseVarianceOverride;
else
    noiseVariance = computeNoiseVariance(h_true,pilotEnergy, ...
        cfg.currentPilotSNRdB,cfg);
end
[Y,W] = simulatePilotReception(h_true,p,pilotEnergy,noiseVariance,activeUE);
y_mk = despreadPilot(Y,p);
h_hat_LS = estimateChannelLS(Y,p,pilotEnergy,activeUE);
[NMSE,meanNMSE,outageMask,outageFraction] = ...
    computeNMSE(h_hat_LS,h_true,cfg.nmseEpsilon);
result = struct('scenario',scenario,'APpos',scenario.APpos, ...
    'UEpos',scenario.UEpos,'obstacles',scenario.obstacles, ...
    'antennaPos',scenario.antennaPos,'h_true',h_true, ...
    'h_hat_LS',h_hat_LS,'h_hat_LMMSE',[], ...
    'pilotAssignment',pilotAssignment,'p',p, ...
    'pilotSNRdB',cfg.currentPilotSNRdB,'pilotEnergy',pilotEnergy, ...
    'noiseVariance',noiseVariance,'Y',Y,'W',W,'y_mk',y_mk, ...
    'activeUE',activeUE,'NMSE',NMSE,'meanNMSE',meanNMSE, ...
    'outageMask',outageMask,'outageFraction',outageFraction, ...
    'pathInfo',pathInfo,'cfg',cfg);
assert(size(result.h_true,1)==cfg.N_AP);
assert(size(result.Y,1)==cfg.N_AP);
assert(isequal(size(result.NMSE),[size(scenario.APpos,1),K]));
end
